# Generated by Django 2.2.2 on 2019-07-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=100)),
                ('quarter', models.IntegerField(default=0)),
            ],
        ),
    ]
