# Generated by Django 2.2.2 on 2019-07-13 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAdmin', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(max_length=25)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryAdmin.Book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryAdmin.Student')),
            ],
        ),
    ]
