# Generated by Django 2.2.2 on 2019-07-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAdmin', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryAdmin.Teacher'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryAdmin.Student'),
        ),
    ]
