# Generated by Django 2.2.2 on 2019-07-20 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAdmin', '0005_auto_20190713_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
