# Generated by Django 2.2.2 on 2019-07-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAdmin', '0007_borrowteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='teacher',
        ),
    ]
